import { UserButton } from '@clerk/nextjs'
import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { api } from '~/utils/api'
import { NextPageWithLayout } from './_app'

const Home: NextPageWithLayout = () => {
  return (
    <>
      {/* <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head> */}
      <div className='flex min-h-screen items-center justify-center dark:bg-gray-800 dark:text-gray-100'>
        <div className='container mx-auto flex flex-col items-center px-4 py-16 text-center md:px-10 md:py-32 lg:px-32 xl:max-w-4xl'>
          <h1 className='text-4xl font-bold leading-none sm:text-5xl'>
            The only AI powered feedback collection
            <span className='dark:text-violet-400'> system </span>
            you will ever need
          </h1>
          <p className='mb-12 mt-8 px-8 text-lg'>
            Accelerate Growth and Improve Customer Experience with AI-Driven Feedback Collection
          </p>
          <div className='flex flex-wrap justify-center'>
            <Link
              href='/auth/signup'
              className='m-2 rounded px-8 py-3 text-lg font-semibold dark:bg-violet-400 dark:text-gray-900'
            >
              Sign up
            </Link>
            <Link
              href='/auth/login'
              className='m-2 rounded border px-8 py-3 text-lg dark:border-gray-700 dark:text-gray-50'
            >
              Log in
            </Link>
          </div>
        </div>
      </div>
    </>
  )
}

export default Home
